// GENERATED by tools/sync-listing-attrs.js from apps/mobile/lib/*.json. Do not edit by hand.
(function (root, factory) {
  var api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.PMListingAttrs = api;
})(typeof window !== 'undefined' ? window : this, function () {
  var SCHEMA = {"vehicles":[{"k":"rentalType","l":"Listing Type"},{"k":"make","l":"Make"},{"k":"model","l":"Model"},{"k":"year","l":"Year"},{"k":"mileage","l":"Mileage","s":"km"},{"k":"fuel","l":"Fuel"},{"k":"transmission","l":"Transmission"},{"k":"bodyType","l":"Body Type"},{"k":"condition","l":"Condition"},{"k":"color","l":"Colour"},{"k":"features","l":"Features","chips":1}],"property":[{"k":"rentalType","l":"Listing Type"},{"k":"propType","l":"Property Type"},{"k":"beds","l":"Bedrooms"},{"k":"baths","l":"Bathrooms"},{"k":"size","l":"Size","s":"m²"},{"k":"furnishing","l":"Furnishing"},{"k":"features","l":"Amenities","chips":1}],"rooms":[{"k":"roomType","l":"Room Type"},{"k":"furnishing","l":"Furnishing"},{"k":"gender","l":"Suitable For"},{"k":"features","l":"Included","chips":1}],"electronics":[{"k":"etype","l":"Type"},{"k":"brand","l":"Brand"},{"k":"condition","l":"Condition"},{"k":"storage","l":"Storage / RAM"},{"k":"warranty","l":"Warranty"}],"furniture":[{"k":"ftype","l":"Type"},{"k":"brand","l":"Brand"},{"k":"condition","l":"Condition"},{"k":"material","l":"Material"}],"fashion":[{"k":"ftype","l":"Type"},{"k":"gender","l":"For"},{"k":"size","l":"Size"},{"k":"color","l":"Colour"},{"k":"fabric","l":"Fabric / Material"},{"k":"condition","l":"Condition"},{"k":"brand","l":"Brand"}],"agriculture":[{"k":"atype","l":"Type"},{"k":"condition","l":"Condition"},{"k":"quantity","l":"Quantity"}],"pets":[{"k":"ptype","l":"Type"},{"k":"breed","l":"Breed"},{"k":"age","l":"Age"},{"k":"gender","l":"Gender"},{"k":"features","l":"Health","chips":1}],"kids":[{"k":"ktype","l":"Type"},{"k":"condition","l":"Condition"},{"k":"ageGroup","l":"Age Group"}],"services":[{"k":"stype","l":"Service Type"},{"k":"availability","l":"Availability"},{"k":"priceBasis","l":"Pricing"}],"other":[{"k":"brand","l":"Brand"},{"k":"condition","l":"Condition"}]};
  var SUBCATS = {"property":{"houses":"Houses","flats":"Flats & Apartments","cottages":"Cottages & Garden Flats","townhouses":"Townhouses & Clusters","stands":"Stands & Land","commercial":"Commercial & Office","student":"Student Accommodation"},"vehicles":{"cars":"Cars","bakkies":"Bakkies & Trucks","suvs":"SUVs & 4x4","kombis":"Kombis & Buses","motorbikes":"Motorbikes","trailers":"Trailers","parts":"Spares & Parts","tyres":"Tyres & Rims"},"rooms":{"single":"Single Rooms","shared":"Shared Rooms","cottage":"Cottages","full-house":"Full House Share","self-contained":"Self-Contained","student":"Student Digs"},"electronics":{"phones":"Phones & Tablets","computers":"Laptops & Computers","tvs":"TVs & Monitors","audio":"Audio & Sound","cameras":"Cameras","gaming":"Gaming","accessories":"Accessories"},"furniture":{"sofas":"Sofas & Lounge","beds":"Beds & Bedroom","dining":"Dining & Kitchen","office":"Office Furniture","outdoor":"Garden & Outdoor","wardrobes":"Wardrobes & Storage","curtains":"Curtains & Blinds","rugs":"Rugs & Carpets","lighting":"Lighting & Fans","decor":"Home Décor"},"fashion":{"clothing":"Clothing","shoes":"Shoes","bags":"Bags & Luggage","watches":"Watches","jewellery":"Jewellery","accessories":"Accessories"},"services":{"home":"Home & Repairs","building":"Building & Construction","tutoring":"Tutoring & Lessons","events":"Events & Catering","beauty":"Beauty & Hair","transport":"Transport & Moving","professional":"Professional Services"},"agriculture":{"livestock":"Livestock","poultry":"Poultry","produce":"Crops & Produce","seeds":"Seeds & Seedlings","equipment":"Farm Equipment","irrigation":"Irrigation","feed":"Feed & Fertiliser"},"pets":{"dogs":"Dogs","cats":"Cats","birds":"Birds","fish":"Fish","farm":"Farm Animals","accessories":"Pet Accessories"},"kids":{"clothing":"Clothing","toys":"Toys","prams":"Prams & Strollers","cots":"Cots & Beds","carseats":"Car Seats","school":"School Items"},"other":{"study-materials":"Study Materials"}};
  function cap(v) {
    var s = String(v).trim();
    return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
  }
  function fmt(v, suffix) {
    var s = Array.isArray(v) ? v.map(cap).join(', ') : cap(v);
    if (suffix && /^\d[\d,.]*$/.test(String(v).trim())) s = Number(String(v).replace(/,/g, '')).toLocaleString('en-US') + ' ' + suffix;
    return s;
  }
  function empty(v) { return v == null || v === '' || (Array.isArray(v) && !v.length); }
  // Returns { specs: [{label, value}], features: {label, items} | null,
  // subcategory: label | null } for a listing's category + attributes.
  function describe(category, attributes, listingCondition) {
    var a = attributes && typeof attributes === 'object' ? attributes : {};
    var fields = SCHEMA[category] || SCHEMA.other || [];
    var specs = [], features = null;
    for (var i = 0; i < fields.length; i++) {
      var f = fields[i], v = a[f.k];
      if (f.k === 'condition' && empty(v)) v = listingCondition;
      if (empty(v)) continue;
      if (f.chips) { features = { label: f.l, items: (Array.isArray(v) ? v : [v]).map(cap) }; continue; }
      specs.push({ label: f.l, value: fmt(v, f.s) });
    }
    var sub = a.subcat && SUBCATS[category] ? (SUBCATS[category][a.subcat] || null) : null;
    return { specs: specs, features: features, subcategory: sub };
  }
  return { describe: describe };
});
