import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './app/App';
import './styles/tokens.css';
import './styles/global.css';
import './styles/layout.css';
import './styles/mfa.css';
import './styles/enterprise.css';
import './styles/listings.css';
import './styles/verifications.css';
import './styles/security-ops.css';
import './styles/reports.css';
const root = document.getElementById('root');
if (!root) throw new Error('Admin root element is missing.');
createRoot(root).render(<StrictMode><App /></StrictMode>);
