import { useMemo, useState } from 'react';

type Incident = { id:string; severity:'P1 HIGH'|'P2 MEDIUM'|'P1 SECURITY'; subsystem:string; file:string; events:number; impact:string; cause:string; gateway:string; trace:string[] };
const incidents: Incident[] = [
  {id:'ERR-4091',severity:'P1 HIGH',subsystem:'ECONNRESET: EcoCash C2B Webhook Timeout',file:'services/escrow/ecocash_gateway.go:184',events:412,impact:'84 shop escrow payments queued in buffer',cause:'Carrier gateway throttling Econet Bulawayo node',gateway:'ECO/PAYNOW',trace:['Exception: dial tcp 196.220.101.44:443: i/o timeout','net/http.(*persistConn).writeLoop','pamarket/services/escrow.(*EcoCashGateway).DispatchWebhook','pamarket/workers/queue.(*Worker).Execute']},
  {id:'ERR-4085',severity:'P2 MEDIUM',subsystem:'OCR Failure: ZIMRA ITF263 Tax Clearance QR',file:'workers/kyc/ocr_parser_zimra.py:49',events:28,impact:'Business verification uploads stalled',cause:'Mobile camera uploads below 150 DPI resolution',gateway:'KYC/OCR',trace:['OCRConfidenceError: minimum threshold not met','kyc/ocr_parser.parseTaxClearance','workers/queue.consumeUpload']},
  {id:'ERR-4072',severity:'P2 MEDIUM',subsystem:'PostGIS Query Slowdown: Harare Stands Radius',file:'db/queries/geo_radius_property.sql:12',events:19,impact:'Spatial query latency escalated to 1,840ms',cause:'Missing GiST index scan on reference partition',gateway:'DATABASE',trace:['QueryTimeout: radius search exceeded 1500ms','property/search.findWithinRadius','postgis/ST_DWithin']},
  {id:'ERR-4050',severity:'P1 SECURITY',subsystem:'Rate Limit Tripped: /api/v1/auth/sms-otp',file:'middleware/security/honeypot_ratelimit.go:91',events:8400,impact:'SMS OTP flood and enumeration attempt',cause:'Reference IP block quarantined at edge',gateway:'SECURITY',trace:['RateLimitExceeded: sms-otp threshold','security/honeypot.detectProbe','edge/firewall.applyReferenceRule']},
];
function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>}
export function ErrorsHealthPage(){
  const [severity,setSeverity]=useState('ALL'); const [gateway,setGateway]=useState('ALL'); const [selectedId,setSelectedId]=useState(incidents[0].id);
  const shown=useMemo(()=>incidents.filter(item=>(severity==='ALL'||item.severity===severity)&&(gateway==='ALL'||item.gateway===gateway)),[severity,gateway]);
  const selected=incidents.find(item=>item.id===selectedId)??shown[0]??incidents[0];
  return <div className="health-page">
    <div className="health-reference" role="note"><Icon name="science"/><b>REFERENCE OBSERVABILITY DATA</b><span>Incidents, infrastructure values and traces are design fixtures. No Sentry or infrastructure telemetry source is connected.</span></div>
    <section className="health-strip">{[['HARARE CENTRAL zw-hre-1','ONLINE','99.98%','Target: 99.95%'],['SENTRY EXCEPTIONS (24H)','8 UNRESOLVED P1','142','Resolved: 134'],['FINTECH GATEWAY PIPELINES','ECOCASH DEGRADED','2.1% err','Other rails: reference healthy'],['REDIS DISPATCH & QUEUES','ZERO DROPS','24ms','Buffered: 1,492 tasks']].map(([title,state,value,note])=><article key={title}><small>{title}</small><b>{state}</b><strong>{value}</strong><span>{note}</span></article>)}</section>
    <div className="health-breadcrumb">PAMARKET OPS / SECURITY & PLATFORM / <b>SYSTEM ERRORS & OBSERVABILITY</b><span>LIVE STREAM: NOT CONNECTED</span></div>
    <header className="health-hero"><div><small>CORE SYSTEM ERRORS, INCIDENTS & EDGE HEALTH</small><h1>Errors & Health</h1><p>Inspect reference edge, payment, database, OCR and security incidents from one operations view.</p></div><nav><button disabled><Icon name="cached"/>PURGE EDGE CACHE</button><button disabled><Icon name="alt_route"/>AUTO-FAILOVER RULES</button><button disabled className="danger"><Icon name="dangerous"/>TERMINATE DB POOL LEAKS</button></nav></header>
    <section className="health-nodes" aria-label="Reference network health">{[['router','Liquid Intelligent Tech','HEALTHY','14ms','Harare Core Node','Packet Loss: 0.00%'],['cell_tower','Econet Wireless (5G/LTE)','DEGRADED','88ms','Bulawayo Tower Subnet','Packet Loss: 3.4%'],['cable','TelOne Zimbabwe','HEALTHY','18ms','EASSy / Mazowe Fibre','Packet Loss: 0.02%'],['satellite_alt','NetOne Cellular','HEALTHY','22ms','OneMoney Relay Net','Packet Loss: 0.08%']].map(([icon,name,state,rtt,node,loss])=><article key={name} className={state==='DEGRADED'?'degraded':''}><Icon name={icon}/><div><strong>{name}</strong><b>{state}</b><span>{node}</span></div><div><strong>{rtt}</strong><small>RTT</small><span>{loss}</span></div></article>)}</section>
    <section className="health-incidents"><header><div><h2>ACTIVE INCIDENTS & TRACED EXCEPTIONS</h2><b>REFERENCE TELEMETRY</b></div><label>SEVERITY<select aria-label="Incident severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option>ALL</option><option>P1 HIGH</option><option>P2 MEDIUM</option><option>P1 SECURITY</option></select></label><label>SUBSYSTEM<select aria-label="Incident subsystem" value={gateway} onChange={e=>setGateway(e.target.value)}><option>ALL</option><option>ECO/PAYNOW</option><option>KYC/OCR</option><option>DATABASE</option><option>SECURITY</option></select></label></header><div className="health-table-scroll"><table aria-label="System incident queue"><thead><tr><th>Incident / Error Hash</th><th>Severity</th><th>Subsystem & Exception</th><th>Events</th><th>Impact & Root Cause</th><th>Mitigation Protocol</th></tr></thead><tbody>{shown.map(item=><tr key={item.id} className={selected.id===item.id?'selected':''}><td><strong>#{item.id}</strong></td><td><b className={`health-severity ${item.severity.includes('P1')?'p1':''}`}>{item.severity}</b></td><td><strong>{item.subsystem}</strong><code>{item.file}</code></td><td><strong>{item.events.toLocaleString()}</strong></td><td><span>{item.impact}</span><small>{item.cause}</small></td><td><button onClick={()=>setSelectedId(item.id)} aria-label={`Inspect ${item.id}`}><Icon name="find_in_page"/>INSPECT TRACE</button><button disabled>MITIGATE</button></td></tr>)}</tbody></table>{!shown.length&&<p role="status">No reference incidents match these filters.</p>}</div><footer>SHOWING {shown.length} OF {incidents.length} REFERENCE INCIDENTS <span>LOG ARCHIVE: NOT CONNECTED</span></footer></section>
    <section className="health-trace" aria-label="Exception trace inspector"><header><Icon name="bug_report"/><div><small>EXCEPTION STACK TRACE & INGRESS CONTEXT</small><h2>TARGET: #{selected.id}</h2><p>TRACE ID: reference-{selected.id.toLowerCase()}</p></div><b>FIXTURE</b></header><div className="health-trace-grid"><article><h3>RUNTIME EXECUTION FRAME</h3><pre>{selected.trace.map((line,index)=>`${String(index+1).padStart(2,'0')}  ${line}`).join('\n')}</pre><h3>TIMEOUT TIMELINE RECONSTRUCTION</h3><div className="health-timeline"><span>CLIENT (0ms)</span><span>INGRESS (14ms)</span><span>DISPATCH (42ms)</span><span>FAILURE THRESHOLD</span></div></article><aside><h3>REFERENCE CONTEXT</h3><dl><div><dt>subsystem</dt><dd>{selected.gateway}</dd></div><div><dt>events</dt><dd>{selected.events.toLocaleString()}</dd></div><div><dt>impact</dt><dd>{selected.impact}</dd></div><div><dt>root cause</dt><dd>{selected.cause}</dd></div></dl><p><Icon name="info"/>Context values are illustrative and contain no production secrets, IP addresses, credentials or customer data.</p><h3>TRIAGE TERMINAL DISPATCH</h3><button disabled>RETRY FAILED WORK (DRY-RUN)</button><button disabled>FORCE FAILOVER</button><button disabled>ACKNOWLEDGE INCIDENT</button></aside></div></section>
  </div>
}
