import { useMemo, useRef, useState } from 'react';

type Job = { id: string; title: string; sector: string; province: string; location: string; company: string; credentials: string; license: string; salary: string; applicants: number; risk: number; complaints: number; status: string };
const jobs: Job[] = [
  { id: 'JOB-ZW-4019', title: 'Senior Agronomist - Mazowe Citrus Estate', sector: 'Agriculture & Farming', province: 'Mashonaland Central', location: 'Mazowe', company: 'Agritech Zimbabwe Ltd', credentials: 'VERIFIED ENTERPRISE · CR14: 84920', license: 'Reference credential only', salary: '$1,200 - $1,500 USD / mo', applicants: 48, risk: 0, complaints: 0, status: 'Active' },
  { id: 'JOB-ZW-4082', title: 'Project Field Assistants (40 Vacancies)', sector: 'NGO / Development', province: 'Midlands', location: 'Gweru', company: 'AfriAid Global HR', credentials: 'UNVERIFIED · 19 EXTORTION COMPLAINTS', license: 'ML-EMP-UNVERIFIED', salary: '$850 USD', applicants: 112, risk: 98, complaints: 19, status: 'Under review' },
  { id: 'JOB-ZW-4077', title: 'Underground Instrumentation Technician', sector: 'Mining & Heavy Engineering', province: 'Mashonaland West', location: 'Ngezi Mine', company: 'Zimplats Operations Base', credentials: 'ZSE-LISTED · CR14: 00192', license: 'Reference credential only', salary: '$2,800 - $3,400 USD / mo', applicants: 19, risk: 0, complaints: 0, status: 'Active' },
  { id: 'JOB-ZW-4065', title: 'Emergency Ambulance Drivers (Fleet of 10)', sector: 'Healthcare & Paramedical', province: 'Bulawayo', location: 'Bulawayo City', company: 'QuickHire Talent Solutions', credentials: 'UNVERIFIED THIRD-PARTY AGENCY', license: 'Not verified', salary: '$500 USD + ZiG 4,500', applicants: 67, risk: 64, complaints: 3, status: 'Under review' },
  { id: 'JOB-ZW-4051', title: 'Lead Mobile Solutions Architect (Flutter/Go)', sector: 'IT & Telecommunications', province: 'Harare', location: 'Borrowdale', company: 'EcoCash Holding Tech Labs', credentials: 'ENTERPRISE SEC-AUDITED · CR14: 99401', license: 'Reference credential only', salary: '$3,500 - $4,200 USD / mo', applicants: 32, risk: 0, complaints: 0, status: 'Active' },
];
const statuses = ['All', 'Active', 'Under review', 'Suspended'];
function Icon({ name }: { name: string }) { return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>; }

export function JobsRecruitersPage() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const [sector, setSector] = useState('All sectors');
  const [province, setProvince] = useState('All provinces');
  const [selected, setSelected] = useState<Job | null>(null);
  const drawer = useRef<HTMLDialogElement>(null);
  const shown = useMemo(() => jobs.filter(job => (status === 'All' || job.status === status) && (sector === 'All sectors' || job.sector === sector) && (province === 'All provinces' || job.province === province) && `${job.id} ${job.title} ${job.company} ${job.location}`.toLowerCase().includes(query.trim().toLowerCase())), [query, status, sector, province]);
  function inspect(job: Job) { setSelected(job); drawer.current?.showModal(); }
  function reset() { setQuery(''); setStatus('All'); setSector('All sectors'); setProvince('All provinces'); }
  return <div className="jobs-page">
    <div className="jobs-reference" role="note"><Icon name="science" /><b>REFERENCE JOB DATA</b><span>Jobs, credentials and risk signals are design samples. Recruiter decisions and candidate notifications are not connected.</span></div>
    <div className="jobs-breadcrumb">PAMARKET OPS / DIRECTORY & COMMERCE / <b>JOBS & RECRUITER VERIFICATION</b><span>LABOUR REGISTER: NOT CONNECTED</span></div>
    <header className="jobs-hero"><div><small>ESDR AUDIT ENGINE <span>CR14 / CREDENTIAL REVIEW</span></small><h1>Jobs & Recruiter Governance Hub</h1><p>Employment feeds, recruiter credential audits, and upfront interview and uniform fee risk review.</p></div><div className="jobs-actions"><button disabled><Icon name="download" />EXPORT CR14 AUDIT LOG</button><button disabled className="danger"><Icon name="security" />BULK INTERVIEW SCAM PURGE</button></div></header>
    <section className="jobs-kpis" aria-label="Reference job metrics">{[
      ['Active Job Posts', '1,840', 'work', '+12% vs last 30d', 'ZIMBABWE NATIONWIDE'],
      ['Pending Recruiter Checks', '14', 'fact_check', 'CR14 & Labour Lic.', 'AVG TRIAGE: 18m'],
      ['Scam Triggers & Fees', '06', 'warning', 'Upfront Uniform/Medical', 'CRITICAL SEVERITY'],
      ['Credits Disbursed', '42,500', 'toll', 'Pool: $127.5k USD eq.', 'REVENUE OPS'],
    ].map(([label, value, icon, detail, foot], index) => <article key={label} className={index === 2 ? 'danger' : ''}><header>{label}<Icon name={icon} /></header><strong>{value}</strong><p>{detail}</p><footer>{foot}<span>SAMPLE</span></footer></article>)}</section>
    <div className="jobs-signals"><section><h2><Icon name="equalizer" />Honeypot Extortion Keyword Triggers <small>24H ROLLING · SAMPLE</small></h2><div className="jobs-keywords">{[['MEDICAL FEE', 18], ['UNIFORM DEPOSIT', 14], ['WHATSAPP INTERVIEW', 42], ['ECOCASH DIRECT', 9]].map(([label, count]) => <article key={label}><span>“{label}”</span><strong>{count} <small>Intercepts</small></strong><div style={{ width: `${Number(count) / 42 * 100}%` }} /></article>)}</div></section><section className="jobs-density"><h2><Icon name="location_on" />Sector Density Radar</h2><b>HARARE CENTRAL</b><p>Mazowe Citrus Agricultural Corridor</p><strong>HIGH DEMAND</strong><footer>Verified Employer Ratio: 94.2% <span>SAMPLE</span></footer></section></div>
    <section className="jobs-filters" aria-label="Filter jobs"><nav aria-label="Job status">{statuses.map(item => <button key={item} aria-pressed={status === item} onClick={() => setStatus(item)}>{item.toUpperCase()} <b>{item === 'All' ? jobs.length : jobs.filter(job => job.status === item).length}</b></button>)}</nav><div><label className="jobs-search"><Icon name="search" /><input aria-label="Search jobs" placeholder="Search job, employer, location or ID" value={query} onChange={event => setQuery(event.target.value)} /></label><select aria-label="Sector" value={sector} onChange={event => setSector(event.target.value)}><option>All sectors</option>{[...new Set(jobs.map(job => job.sector))].map(item => <option key={item}>{item}</option>)}</select><select aria-label="Province" value={province} onChange={event => setProvince(event.target.value)}><option>All provinces</option>{[...new Set(jobs.map(job => job.province))].map(item => <option key={item}>{item}</option>)}</select><button onClick={reset}><Icon name="filter_alt_off" />RESET FILTERS</button></div></section>
    <section className="jobs-ledger"><div className="jobs-table-scroll"><table aria-label="Jobs and recruiter review queue"><thead><tr>{['Job Designation & Identifier', 'Employer / Recruiter Entity', 'Remuneration (USD/ZiG)', 'Applicant Volume', 'Upfront Fee Risk', 'Ops Interventions'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{shown.map(job => <tr key={job.id} className={job.risk > 70 ? 'critical' : ''}><td><strong>{job.title}</strong>{job.risk > 0 && <b className="jobs-risk-label">{job.risk > 70 ? 'SCAM TRIGGER' : 'FEES REPORTED'}</b>}<small>#{job.id} · {job.sector}</small><small>{job.location}, {job.province}</small></td><td><strong>{job.company}</strong><small>{job.credentials}</small></td><td><strong>{job.salary}</strong><small>{job.status}</small></td><td><strong className="jobs-volume">{job.applicants}</strong><small>Applications</small></td><td><b className={`jobs-risk ${job.risk > 70 ? 'high' : job.risk ? 'moderate' : ''}`}>{job.risk}% {job.risk > 70 ? 'CRITICAL' : job.risk ? 'MODERATE' : 'SAFE'}</b></td><td><button onClick={() => inspect(job)} aria-label={`Inspect ${job.id}`}><Icon name="find_in_page" />{job.risk ? 'INSPECT CASE' : 'AUDIT DOCS'}</button><button disabled>{job.risk > 70 ? 'SUSPEND NOW' : job.risk ? 'HOLD ESCROW' : 'APPROVE'}</button></td></tr>)}</tbody></table>{!shown.length && <div className="jobs-empty" role="status">No reference jobs match these filters. <button onClick={reset}>Clear filters</button></div>}</div><footer aria-live="polite">SHOWING {shown.length} OF {jobs.length} REFERENCE VACANCIES <span>LIVE JOB FEED: NOT CONNECTED</span></footer></section>
    <section className="jobs-policy"><Icon name="verified_user" /><div><h2>Recruiter Credential & Fee Policy Review</h2><p>Review incorporation documents, labour credentials and reported candidate fees before making a moderation decision.</p></div><button disabled>MINISTRY LABOUR REGISTER</button></section>
    <dialog ref={drawer} className="jobs-drawer" aria-labelledby="job-dossier-title" onClick={event => { if (event.target === drawer.current) drawer.current.close(); }}>
      {selected && <div><header><div><small>FORENSIC DOSSIER · REFERENCE DATA</small><p>#{selected.id}</p><h2 id="job-dossier-title">{selected.company}</h2></div><button aria-label="Close forensic dossier" onClick={() => drawer.current?.close()} autoFocus><Icon name="close" /></button></header><section><h3>{selected.title}</h3><p>{selected.location}, {selected.province}</p><div className="jobs-credentials"><article><small>Companies Office (CR14)</small><strong>{selected.credentials}</strong></article><article><small>Ministry Labour Lic.</small><strong>{selected.license}</strong></article></div><b className={`jobs-risk ${selected.risk > 70 ? 'high' : selected.risk ? 'moderate' : ''}`}>{selected.risk}% FEE RISK · SAMPLE</b></section><section><h3>Incorporation Deed Preview</h3><div className="jobs-document"><Icon name="find_in_page" /><span>No document connected for this reference record.</span></div></section><section><h3>Whistleblower Complaints ({selected.complaints})</h3>{selected.id === 'JOB-ZW-4082' ? <><blockquote>“They reached out on WhatsApp claiming I passed initial CV screening, but required a $25 USD EcoCash deposit for police clearance and uniform fitting prior to interview.”<footer>Sample candidate report · Harare</footer></blockquote><blockquote>“Solicits a non-refundable administrative processing charge.”<footer>Sample candidate report · Gweru</footer></blockquote></> : <p>{selected.complaints ? 'Complaint details are not available in this reference dossier.' : 'No complaints in this reference dossier.'}</p>}</section><section><h3>Recruiter Review Summary</h3><dl><div><dt>Applications</dt><dd>{selected.applicants}</dd></div><div><dt>Listing state</dt><dd>{selected.status}</dd></div><div><dt>Credential verification</dt><dd>Not connected</dd></div><div><dt>Wallet / IP evidence</dt><dd>Not connected</dd></div></dl></section><footer><p>Enforcement actions require connected, audited server handlers.</p><div className="jobs-actions"><button disabled><Icon name="campaign" />WARN CANDIDATES</button><button disabled>REFER TO LABOUR POLICE</button><button disabled className="danger"><Icon name="block" />BAN RECRUITER & EXPUNGE POSTINGS</button></div></footer></div>}
    </dialog>
  </div>;
}
