import { useMemo, useState } from 'react';

type Listing = { id:string; title:string; meta:string; images:number; category:string; location:string; seller:string; sellerMeta:string; trust:string; price:string; terms:string; signal:string; signalDetail:string; risk:'clear'|'danger'; age:string; sla:string; image:string };
const listings: Listing[] = [
  {id:'ZW-LST-88491',title:'2018 Toyota Hilux D4D 2.8 GD-6 Double Cab',meta:'VIN: AHTFZ29G90...',images:8,category:'Vehicles > Bakkies',location:'Harare (Belvedere West)',seller:'Farai M. Chiweshe',sellerMeta:'+263 77 289 **** · ID: 63-2940182-K',trust:'Trust Score: 94% (4th Listing)',price:'$24,500',terms:'Cash / Escrow Bank',signal:'DUPLICATE PHOTO DETECTED',signalDetail:'Matched FB Marketplace SA (Durban)',risk:'danger',age:'14 mins ago',sla:'SLA: 46m remaining',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuBtsP0hR3TAvT1evR_whJovlo72ohvTGRybCU7FoyeHSQ8fooZos5EpAGtqqibC1ynWetMJq1zHTw_gov4ECddD7gQLRQAAl4CELfg-RXEDbXlTltNkUWCzeENlHLqgnvcoqVu3B81hFH0yUBB92V6nTQ_l_e4aQpNHfyLpiwj65ygQLJJcdvy6dqeM7-YX9lg5y2y99yF0DwDUOkl4I_KbJLKwRKdMdcUgGHSMiUkHZvew3aNGjBfj4Q'},
  {id:'ZW-LST-88492',title:'3 Bedroom House in Glen Lorne, Harare East',meta:'Deed No: 4892/2014',images:16,category:'Real Estate > Residential',location:'Harare (Glen Lorne)',seller:'Dawn Properties Agent',sellerMeta:'+263 24 278 **** · REA Cert #104',trust:'Trust Score: 99% (Agency)',price:'$185,000',terms:'Title Deeds Available',signal:'DEEDS REGISTRY MATCHED',signalDetail:'Survey diagram attached (PDF)',risk:'clear',age:'32 mins ago',sla:'SLA: 28m remaining',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuA4EajQIMTiyGVm3fgSR3nOy-n-2UicTEDExD31JJPnaffc35ERBXRIesw6c2uOAdJeJttXGNL7govbqJxUOo6YLOcscbnwGXjuywyb6pffctTddaYcvRDeszKBwHs38Yp5x16bCkgW55_OPcmxfzd2CD9xw-v6JuwUaLge59t-yLVxxk7S5XmI58Ub_enK6d6IyvazBhU8t0BmmYhtVBCqsLRrvqfC5RSW6WwcpvRsJYxRn7pL3AX6BQ'},
  {id:'ZW-LST-88493',title:'John Deere 5075E 4WD Tractor (620 Hours)',meta:'Hourmeter Verified',images:6,category:'Farming > Tractors & Implements',location:'Mash Central (Mazowe)',seller:'Simbarashe Ndoro',sellerMeta:'+263 71 455 **** · ID: 44-1928371-R',trust:'Trust Score: 98% (EcoCash KYC Level 3)',price:'$22,000',terms:'Negotiable / Bank Transfer',signal:'LOW RISK (SCORE 08)',signalDetail:'Original invoice verified',risk:'clear',age:'41 mins ago',sla:'SLA: 19m remaining',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuCneYyKvB8GtLerxfIlovvenVca1rJVHrby_-V9XSgevtaT-j8FrjcY7xO43258OxlW8W7HJrKAISSUP3zy0VrLJG2kKddxo61jydVZVV8S7WjdmwIVua5QscLqu7VAGneMrkglO_IzB49TpemIkPtxh0pEc7fYuX8iPqzHsls7XT0zsNDyU46CDheXeO31fxQtezRdfmmNW6uU8-bjuX0_6wymagHjNIS3nTtLaGyzHMg_Tz86m4DGjA'},
  {id:'ZW-LST-88494',title:'Apple iPhone 15 Pro Max 256GB Sealed',meta:'IMEI: Pending Input',images:3,category:'Electronics > Mobile Phones',location:'Bulawayo (CBD)',seller:'Kudzi_Gadgets_ZW',sellerMeta:'+263 78 991 **** · Age: 2 days',trust:'Trust Score: 31% (Unverified ID)',price:'$420',terms:'-68% Under Market ($1,250)',signal:'PRICE COLLAPSE ANOMALY',signalDetail:'Likely advance-fee fraud vector',risk:'danger',age:'5 mins ago',sla:'SLA: 55m remaining',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuBLZRqk4n_0S9lysZfkD_UhYmtdDKFIJ2pYWsat9Pwd_7rQD_Alyx5VrRhQP76KdosQwo0FiesdxLwMC_rcTI1ugNNDQz8BLkwuz1XZWC_OOq98xJTFXG_ZVdVt7YJgPNAMp8U2bK6dte0EKYOCXENHQb3vaL_9e9LyraUTUT3Q4yzeHNc_N06zB2TVpz6a-M_OXvdGcsmlrwryTqNRy8CJgzSddSJBXGAiV6peV43jbOu0XcPfXchwGg'},
  {id:'ZW-LST-88495',title:'Deye 10kW Hybrid Inverter + Felicity 15kWh Lithium',meta:'Serial Barcode OK',images:5,category:'Solar & Power > Inverters',location:'Harare (Msasa Industrial)',seller:'ZimPower Systems Ltd',sellerMeta:'+263 77 100 **** · TIN: 2000847192',trust:'Trust Score: 97% (Verified Store)',price:'$3,850',terms:'Direct Bank / ZiG Equivalent',signal:'AUTHORIZED DISTRIBUTOR',signalDetail:'Warranty SLA attached',risk:'clear',age:'18 mins ago',sla:'SLA: 42m remaining',image:'https://lh3.googleusercontent.com/aida-public/AB6AXuCpV2E_jrFym3467qIs0-ky_dDdUHdMosuYbLWZLcMVD3mU2GgomThCm4mietGdar7oD1WooQHiH7CFWRMlD8z3JCaWdZgwl1kta1Ss5-abDlXR1-_pVY0d9eCb27fXNF58XOhNaVSzW8smGxtgNVghEd4WI7p9AixFbzkG7MirE3t7d48Cd7zRhL73tMW2WrcXf2iEHDTYMxL5ntqevpt3i4nSe7a06dau4OW-kpJ4MDzoCCPq6QMRHw'}
];
const tabs = [['Pending Review','384'],['Flagged / Reported','19'],['Requires Changes','42'],['Approved','41,200'],['Rejected','1,150']];

export function ListingsModerationPage() {
  const [activeTab,setActiveTab]=useState('Pending Review'); const [query,setQuery]=useState(''); const [province,setProvince]=useState('All Provinces'); const [risk,setRisk]=useState('All Risk Signals');
  const [selected,setSelected]=useState(()=>new Set(['ZW-LST-88491','ZW-LST-88492'])); const [inspected,setInspected]=useState<Listing|null>(null);
  const shown=useMemo(()=>listings.filter(item=>`${item.id} ${item.title} ${item.seller}`.toLowerCase().includes(query.toLowerCase())&&(province==='All Provinces'||item.location.startsWith(province))&&(risk==='All Risk Signals'||item.risk===risk)),[query,province,risk]);
  const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id)) next.delete(id); else next.add(id);return next});
  return <div className="listing-ops">
    <div className="listing-reference" role="note"><span className="material-symbols-outlined">science</span><b>REFERENCE CASE DATA</b><span>This screen matches the approved operations design. Server-side moderation actions remain locked until audited handlers are connected.</span></div>
    <section className="listing-kpis"><article><span>HARARE QUEUE VELOCITY</span><strong>384</strong><b>+18/hr</b><small>Avg Triage Wait <em>8.4m</em></small></article><article><span>ESCROW COMPLIANCE SLA</span><strong>99.1%</strong><b>ON TARGET</b><small>Target threshold <em>98.0%</em></small></article><article><span>AI FORENSIC FLAGGED</span><strong className="warn">19</strong><b>ITEMS</b><small>Critical review <em>4</em></small></article><article><span>ZIM-ID AUTO-MATCH</span><strong>92.4%</strong><b>VERIFIED</b><small>Manual fallback <em>7.6%</em></small></article></section>
    <nav className="listing-tabs" aria-label="Listing states">{tabs.map(([label,count])=><button key={label} className={activeTab===label?'active':''} onClick={()=>setActiveTab(label)}>{label}<b>{count}</b></button>)}</nav>
    <section className="listing-filter" aria-label="Moderation filters"><label className="filter-search"><span className="material-symbols-outlined">search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Listing ID, title, phone or National ID" /></label><select value={province} onChange={e=>setProvince(e.target.value)} aria-label="Province"><option>All Provinces</option><option>Harare</option><option>Bulawayo</option><option>Mash Central</option></select><select aria-label="Category"><option>All Categories</option><option>Vehicles</option><option>Property</option><option>Electronics</option></select><select value={risk} onChange={e=>setRisk(e.target.value)} aria-label="Risk Matrix"><option>All Risk Signals</option><option value="danger">Critical / Suspicious</option><option value="clear">Verified / Low Risk</option></select><button className="query-button"><span className="material-symbols-outlined">manage_search</span>Query</button><button onClick={()=>{setQuery('');setProvince('All Provinces');setRisk('All Risk Signals')}}>Reset</button></section>
    <section className="bulk-strip"><div><span className="material-symbols-outlined">checklist</span><strong>{selected.size} / 384 SELECTED</strong><span>BATCH ID: PM-HRE-0912</span></div><div><button disabled>Approve Selected</button><button disabled>Reject Selected</button><button disabled>Request Seller Changes</button><button disabled>Escalate to Senior</button></div></section>
    <section className="moderation-grid"><div className="listing-table-scroll"><table aria-label="Pending Listings Moderation Grid"><thead><tr><th aria-label="Selection"/><th>Listing Spec & Artifacts</th><th>Classification & Geo</th><th>Seller Ledger & KYC</th><th>Price Valuation</th><th>Forensic Signal Matrix</th><th>SLA Wait Clock</th><th>Triage Action</th></tr></thead><tbody>{shown.map((item,index)=><tr key={item.id} className={index%2?'alternate':''}><td><input type="checkbox" aria-label={`Select listing ${item.id}`} checked={selected.has(item.id)} onChange={()=>toggle(item.id)} /></td><td><div className="listing-spec"><div className="listing-thumb"><img src={item.image} alt="" /><span>{item.images} img</span></div><div><strong>{item.title}</strong><small><b>#{item.id}</b> · {item.meta}</small></div></div></td><td><strong>{item.category}</strong><small><span className="material-symbols-outlined">location_on</span>{item.location}</small></td><td><strong>{item.seller} <span className="verified material-symbols-outlined">verified</span></strong><small>{item.sellerMeta}</small><small className={item.risk==='danger'?'danger-text':'trust'}>{item.trust}</small></td><td><strong className={`price ${item.risk==='danger'?'danger-text':''}`}>{item.price} <small>USD</small></strong><small>{item.terms}</small></td><td><b className={`signal ${item.risk}`}>{item.signal}</b><small className={item.risk==='danger'?'danger-text':''}>{item.signalDetail}</small></td><td><strong>{item.age}</strong><small className="sla"><span className="material-symbols-outlined">alarm</span>{item.sla}</small></td><td><div className="triage"><button disabled>Approve</button><button disabled>Reject</button><button onClick={()=>setInspected(item)} title="Inspect Full Dossier"><span className="material-symbols-outlined">visibility</span></button></div></td></tr>)}</tbody></table></div>
    <footer className="listing-pagination"><span>SHOWING {shown.length?`1 - ${shown.length}`:'0'} OF 384 RECORDS</span><span>BATCH BUFFER: <b>2.4 MB (FAST)</b></span><div><button disabled>‹</button><b>1</b><button>2</button><button>3</button><span>…</span><button>16</button><button>›</button></div></footer></section>
    {inspected&&<><button className="drawer-scrim" aria-label="Close forensic dossier" onClick={()=>setInspected(null)} /><aside className="forensic-drawer" aria-label="Forensic dossier"><header><div><span className="material-symbols-outlined">biotech</span><span><strong>FORENSIC DOSSIER</strong><small>#{inspected.id}</small></span></div><button onClick={()=>setInspected(null)} aria-label="Close"><span className="material-symbols-outlined">close</span></button></header><div className="drawer-body"><div className="drawer-image"><img src={inspected.image} alt=""/><span>GEO / EXIF EVIDENCE · REFERENCE RECORD</span></div><section><label>KYC IDENTITY RECORD</label><div className="dossier-grid"><p><small>SELLER</small><strong>{inspected.seller}</strong></p><p><small>LISTING ID</small><strong>#{inspected.id}</strong></p><p><small>LOCATION</small><strong>{inspected.location}</strong></p><p><small>SECURITY SIGNAL</small><strong>{inspected.signal}</strong></p></div></section><section><label>AUTOMATED FORENSIC TELEMETRY</label><p className={`forensic-signal ${inspected.risk}`}><span>{inspected.signalDetail}</span><b>{inspected.risk==='danger'?'REVIEW':'CLEAR'}</b></p></section></div><footer><button disabled>Reject with Reason</button><button disabled>Approve Listing</button></footer></aside></>}
  </div>;
}
