// Existing Privacy Data Export page. Platform counts use existing RLS;
// subject records use the super_admin/AAL2-gated privacy_export_subject RPC.
import { useCallback, useState } from 'react';
import { useAuth } from '../security/auth-context';
import { generatePrivacySnapshot, type PrivacySnapshot } from '../services/privacy-export/query';

function Icon({ name }: { name: string }) { return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>; }

function fmtDate(iso: string) {
  return new Intl.DateTimeFormat('en-ZW', { dateStyle: 'medium', timeStyle: 'medium', timeZone: 'Africa/Harare' }).format(new Date(iso));
}

function buildPrintableHtml(snapshot: PrivacySnapshot): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  const sections = snapshot.sections.map((s) => `
    <section>
      <h2>${esc(s.title)}</h2>
      <p class="desc">${esc(s.description)}</p>
      ${s.source ? `<p class="note">Source: ${esc(s.source)}</p>` : ''}
      ${s.metrics.length ? `<table><tbody>${s.metrics.map((m) => `<tr><th>${esc(m.label)}</th><td>${esc(m.value)}${m.note ? `<div class="note">${esc(m.note)}</div>` : ''}</td></tr>`).join('')}</tbody></table>` : ''}
      ${s.records?.length ? `<table><thead><tr><th>Record ID</th><th>Recorded fields</th></tr></thead><tbody>${s.records.map((r) => `<tr><td>${esc(String(r.id ?? r.user_id ?? 'N/A'))}</td><td><pre>${esc(JSON.stringify(r, null, 2))}</pre></td></tr>`).join('')}</tbody></table>` : ''}
      ${s.caveats.length ? `<ul class="caveats">${s.caveats.map((cv) => `<li>${esc(cv)}</li>`).join('')}</ul>` : ''}
    </section>`).join('\n');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>PaMarket ${snapshot.subjectId ? 'Subject Access Export' : 'Privacy Compliance Snapshot'} — ${esc(snapshot.generatedAt)}</title>
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; max-width: 860px; margin: 40px auto; padding: 0 24px; line-height: 1.5; }
    h1 { font-size: 22px; border-bottom: 3px solid #1a1a1a; padding-bottom: 12px; }
    h2 { font-size: 16px; margin-top: 32px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
    .meta { font-size: 13px; color: #444; margin-bottom: 24px; }
    .meta div { margin: 2px 0; }
    .desc { font-size: 13px; color: #333; font-style: italic; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 13px; }
    th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid #e0e0e0; vertical-align: top; }
    th { width: 55%; font-weight: 600; }
    .note { color: #666; font-size: 11px; margin-top: 2px; }
    pre { white-space: pre-wrap; overflow-wrap: anywhere; font: 11px/1.4 Consolas, monospace; }
    tr { break-inside: avoid; }
    .caveats { background: #fff8e6; border: 1px solid #e8d9a0; padding: 10px 16px; font-size: 12.5px; margin-top: 8px; }
    .caveats li { margin: 4px 0; }
    footer { margin-top: 40px; font-size: 11px; color: #888; border-top: 1px solid #ccc; padding-top: 10px; }
    @media print { body { margin: 0; } }
  </style></head>
  <body>
    <h1>PaMarket — ${snapshot.subjectId ? 'Limited Subject Access Export' : 'Privacy / Data Protection Compliance Snapshot'}</h1>
    <div class="meta">
      <div><b>Report generated:</b> ${esc(fmtDate(snapshot.generatedAt))} (${esc(snapshot.generatedAt)})</div>
      <div><b>Generated by:</b> ${esc(snapshot.generatedBy.name)} (${esc(snapshot.generatedBy.email)}) — role: ${esc(snapshot.generatedBy.role)}, admin ID ${esc(snapshot.generatedBy.id)}</div>
      <div><b>Scope:</b> ${snapshot.subjectId ? `Limited subject-linked export for user ${esc(snapshot.subjectId)}` : 'Platform-wide compliance snapshot'}. Live records as of the generation time.</div>
    </div>
    ${sections}
    <footer>Generated by the PaMarket Admin privacy-export tool. Review scope, source limitations and third-party information before disclosure. This export has not been validated as a complete regulatory response. No historical records are inferred.</footer>
  </body></html>`;
}

export function PrivacyExportPage() {
  const auth = useAuth();
  const [snapshot, setSnapshot] = useState<PrivacySnapshot | null>(null);
  const [phase, setPhase] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle');
  const [error, setError] = useState<string | null>(null);
  const [subjectId, setSubjectId] = useState('');

  const canExport = auth.identity?.permissions.includes('privacy.export') ?? false;

  const generate = useCallback(async () => {
    if (auth.mode !== 'live' || !auth.identity) { setError('Live Supabase session required to generate this report.'); setPhase('error'); return; }
    setPhase('loading');
    setError(null);
    setSnapshot(null);
    const result = await generatePrivacySnapshot({
      id: auth.identity.id,
      name: auth.identity.name,
      email: auth.identity.email ?? auth.identity.displayEmail ?? 'unknown',
      role: auth.identity.role,
    }, subjectId.trim() || undefined);
    if (result.error) { setError(result.error.message); setPhase('error'); return; }
    setSnapshot(result.data);
    setPhase('ready');
  }, [auth.mode, auth.identity, subjectId]);

  const downloadHtml = useCallback(() => {
    if (!snapshot) return;
    const html = buildPrintableHtml(snapshot);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pamarket-${snapshot.subjectId ? `sar-${snapshot.subjectId}` : 'privacy-snapshot'}-${snapshot.generatedAt.slice(0, 19).replace(/[:T]/g, '-')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [snapshot]);

  const printReport = useCallback(() => {
    if (!snapshot) return;
    const html = buildPrintableHtml(snapshot);
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  }, [snapshot]);

  return <div className="directory-page">
    {auth.mode === 'mock' && <div className="directory-reference" role="note"><Icon name="science" /><b>REFERENCE DATA MODE</b><span>Live Supabase is not configured in this environment — this report cannot be generated here.</span></div>}
    <div className="directory-breadcrumb">PAMARKET OPS / SECURITY &amp; PLATFORM / <b>PRIVACY DATA EXPORT</b></div>
    <header className="directory-hero"><div><small>DPO / COMPLIANCE</small><h1>Privacy Data Export</h1>
      <p>Generates a dated platform compliance report from live records. Enter a user ID to append an individual subject access export. Empty registers are identified explicitly.</p>
    </div></header>

    {!canExport && <div className="directory-empty" role="alert">Your role does not have the <code>privacy.export</code> permission. This export is restricted to Super Admin because it aggregates across nearly every table holding personal data.</div>}

    {canExport && <section className="directory-filters" aria-label="Generate"><div>
      <label>Subject user ID (optional) <input type="text" value={subjectId} onChange={(e) => setSubjectId(e.target.value)} placeholder="UUID for SAR export" /></label>
      <button onClick={() => void generate()} disabled={phase === 'loading'}><Icon name="fact_check" />{phase === 'loading' ? 'Generating…' : 'Generate snapshot'}</button>
      {snapshot && <button onClick={printReport}><Icon name="print" />Print / Save as PDF</button>}
      {snapshot && <button onClick={downloadHtml}><Icon name="download" />Download HTML</button>}
    </div></section>}

    {phase === 'error' && <div className="directory-empty" role="alert">Could not generate report: {error}</div>}

    {snapshot && <section className="directory-ledger">
      <header><span>Generated {fmtDate(snapshot.generatedAt)} by {snapshot.generatedBy.name} ({snapshot.generatedBy.role})</span></header>
      <div style={{ padding: '16px 20px' }}>
        {snapshot.sections.map((s) => <div key={s.id} style={{ marginBottom: 28 }}>
          <h3 style={{ marginBottom: 4 }}>{s.title}</h3>
          <p style={{ fontSize: 13, color: 'var(--muted, #666)', fontStyle: 'italic', marginTop: 0 }}>{s.description}</p>
          {s.source && <small>Source: {s.source}</small>}
          {s.metrics.length > 0 && <table aria-label={s.title}><tbody>
            {s.metrics.map((m, i) => <tr key={i}><th style={{ textAlign: 'left', width: '55%' }}>{m.label}</th><td>{m.value}{m.note && <div style={{ fontSize: 11, color: '#888' }}>{m.note}</div>}</td></tr>)}
          </tbody></table>}
          {s.records && <p><small>{s.records.length} record(s) included in downloadable HTML / PDF.</small></p>}
          {s.caveats.length > 0 && <ul style={{ background: 'rgba(232,180,40,0.1)', border: '1px solid rgba(200,150,30,0.4)', padding: '8px 20px', fontSize: 12.5, borderRadius: 6 }}>
            {s.caveats.map((cv, i) => <li key={i} style={{ margin: '4px 0' }}>{cv}</li>)}
          </ul>}
        </div>)}
      </div>
    </section>}

  </div>;
}
