import { useMemo, useState } from 'react';
import { useAuth } from '../security/auth-context';
import { adminRoles, rolePermissions, type AdminRole, type Permission } from '../security/permissions';

const roleMeta:Record<AdminRole,{label:string;tier:string;count:number}>={super_admin:{label:'Super Admin',tier:'TIER 0 · ROOT',count:2},admin:{label:'Operations Admin',tier:'TIER 1 · OPERATIONS',count:5},moderator:{label:'Trust & Moderation',tier:'TIER 2 · MODERATION',count:7},support:{label:'Support Agent',tier:'TIER 3 · SUPPORT',count:3},finance:{label:'Finance & Escrow',tier:'TIER 1 · FINANCE',count:1}};
const staff=[
 {id:'ADM-ZW-99214',name:'Tinashe Moyo',initials:'TM',role:'super_admin' as AdminRole,terminal:'Harare Ops Terminal',credential:'YubiKey 5C NFC · Reference',session:'Active · reference session'},
 {id:'ADM-ZW-99042',name:'Chipo Kanyemba',initials:'CK',role:'super_admin' as AdminRole,terminal:'Bulawayo Regional Hub',credential:'YubiKey 5 FIPS · Reference',session:'Idle 24m · reference session'},
 {id:'ADM-ZW-88104',name:'Blessing Chirume',initials:'BC',role:'admin' as AdminRole,terminal:'Harare Operations',credential:'FIDO2 credential · Reference',session:'Active · reference session'},
 {id:'ADM-ZW-77192',name:'Farai Sibanda',initials:'FS',role:'moderator' as AdminRole,terminal:'Trust & Safety Desk',credential:'FIDO2 credential · Reference',session:'Active · reference session'},
 {id:'ADM-ZW-66218',name:'Rudo Ncube',initials:'RN',role:'support' as AdminRole,terminal:'Bulawayo Support',credential:'MFA credential · Reference',session:'Offline · reference session'},
 {id:'ADM-ZW-55310',name:'Tafadzwa Dube',initials:'TD',role:'finance' as AdminRole,terminal:'Finance Terminal',credential:'FIDO2 credential · Reference',session:'Active · reference session'},
];
const domains:[string,string,Permission[]][]=[['fact_check','Trust & Moderation',['listings.view','listings.moderate','verifications.manage','reports.view','reports.manage','moderation.manage','reviews.moderate']],['account_balance','Commerce & Revenue',['orders.view','orders.manage','monetization.view','revenue.view','ads.view','ads.manage','billing.view']],['security','Platform Governance',['audit.view','audit.export','errors.view','errors.resolve','operations.view','security.view','security.manage','admins.manage','mfa_policy.manage','settings.manage']],['domain','Marketplace Operations',['users.view','users.assist','businesses.view','rentals.view','rentals.moderate','rentals.manage','taxonomy.view','taxonomy.manage']]];
function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>}
function formatPermission(permission:Permission){return permission.split('.').map(x=>x[0].toUpperCase()+x.slice(1)).join(' · ')}
export function RolesPermissionsPage(){
 const auth=useAuth(); const [role,setRole]=useState<AdminRole>('super_admin'); const [selectedId,setSelectedId]=useState(staff[0].id); const [query,setQuery]=useState('');
 const assigned=useMemo(()=>staff.filter(person=>person.role===role&&`${person.name} ${person.id} ${person.terminal}`.toLowerCase().includes(query.toLowerCase())),[role,query]);
 const selected=staff.find(person=>person.id===selectedId)??staff[0]; const allowed=new Set(rolePermissions[role]);
 return <div className="rbac-page">
  <div className="rbac-reference" role="note"><Icon name="science"/><b>REFERENCE STAFF DATA</b><span>Role definitions use the application’s real permission map. Staff, credentials, sessions and requests are design fixtures; no admin mutation is connected.</span></div>
  <div className="rbac-breadcrumb">PAMARKET OPS / SECURITY & PLATFORM / <b>ROLES & PERMISSIONS</b><span>RBAC GUARD: ACTIVE</span></div>
  <header className="rbac-hero"><div><h1>Staff Roles, Permissions & Access Governance</h1><p>Inspect least-privilege role definitions, hardware-token policy and module access across operations terminals.</p></div><nav><button disabled><Icon name="history"/>AUDIT LOGS</button><button disabled><Icon name="person_add"/>PROVISION OPERATOR</button></nav></header>
  <section className="rbac-kpis">{[['shield_person','Active Staff Force','18','5 application roles'],['key','AAL2 Hardware Token','POLICY','Sensitive routes require AAL2'],['approval_delegation','Privilege Requests','02','REFERENCE REQUESTS'],['lock_clock','Emergency Break-Glass','SEALED','0 overrides']].map(([icon,label,value,note],index)=><article key={label} className={index>1?'warning':''}><header>{label}<Icon name={icon}/></header><strong>{value}</strong><p>{note}</p><footer>SAMPLE OPERATIONS DATA</footer></article>)}</section>
  <nav className="rbac-roles" aria-label="Administrative roles">{adminRoles.map(item=><button key={item} aria-pressed={role===item} onClick={()=>{setRole(item);setQuery('');setSelectedId(staff.find(person=>person.role===item)?.id??staff[0].id)}}><span>{roleMeta[item].label}<small>{roleMeta[item].tier}</small></span><b>{roleMeta[item].count}</b></button>)}</nav>
  <section className="rbac-role-header"><Icon name="admin_panel_settings"/><div><small>SELECTED ROLE</small><h2>{roleMeta[role].label}</h2><p>{roleMeta[role].tier} · {rolePermissions[role].length} permissions defined in application code</p></div><button disabled><Icon name="tune"/>Edit Role Policy</button><button disabled><Icon name="block"/>Revoke Role Sessions</button></section>
  <div className="rbac-workspace"><section className="rbac-staff"><header><h2>ASSIGNED STAFF</h2><label><Icon name="search"/><input aria-label="Search assigned staff" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search operator or terminal"/></label></header><div className="rbac-table-scroll"><table aria-label="Assigned administrative staff"><thead><tr><th>Operator</th><th>Department / Terminal</th><th>AAL2 Credential</th><th>Session</th><th>Access</th></tr></thead><tbody>{assigned.map(person=><tr key={person.id} className={selected.id===person.id?'selected':''}><td><span className="rbac-avatar">{person.initials}</span><strong>{person.name}</strong><small>{person.id}</small></td><td>{person.terminal}</td><td>{person.credential}</td><td>{person.session}</td><td><button aria-label={`Inspect ${person.name}`} onClick={()=>setSelectedId(person.id)}>INSPECT</button><button disabled>REVOKE</button></td></tr>)}</tbody></table>{!assigned.length&&<p role="status">No reference staff match this role and search.</p>}</div></section><aside className="rbac-operator" aria-label="Selected operator"><header><span className="rbac-avatar">{selected.initials}</span><div><small>REFERENCE OPERATOR</small><h2>{selected.name}</h2><p>{selected.id}</p></div></header><dl><div><dt>Assigned role</dt><dd>{roleMeta[selected.role].label}</dd></div><div><dt>Terminal</dt><dd>{selected.terminal}</dd></div><div><dt>Credential</dt><dd>{selected.credential}</dd></div><div><dt>Session</dt><dd>{selected.session}</dd></div></dl><p>This inspector contains no live network address, hardware serial, email, or session token.</p></aside></div>
  <section className="rbac-matrix"><header><div><Icon name="grid_4x4"/><span><h2>RBAC Permission Matrix by Marketplace Domain</h2><p>Selected role: <b>{roleMeta[role].label}</b></p></span></div><div className="rbac-legend"><span>● Permitted</span><span>○ Restricted</span></div></header>{domains.map(([icon,label,permissions])=><article key={label}><h3><Icon name={icon}/>{label}<small>{permissions.filter(permission=>allowed.has(permission)).length}/{permissions.length} permitted</small></h3><div>{permissions.map(permission=><span key={permission} className={allowed.has(permission)?'allowed':'restricted'}><Icon name={allowed.has(permission)?'check_circle':'lock'}/><b>{formatPermission(permission)}</b><small>{allowed.has(permission)?'PERMITTED':'RESTRICTED'}</small></span>)}</div></article>)}</section>
  <div className="rbac-bottom"><section><header><Icon name="verified_user"/><h2>Security Baseline & Hardware Token Directives</h2></header><dl><div><dt>AAL2 requirement</dt><dd>Enforced by protected routes and sensitive actions</dd></div><div><dt>Current signed-in role</dt><dd>{auth.identity?.role??'Unavailable'}</dd></div><div><dt>Current assurance</dt><dd>{auth.assuranceLevel?.toUpperCase()??'Unavailable'}</dd></div><div><dt>Session invalidation</dt><dd>Backend operation required</dd></div></dl></section><section><header><Icon name="gavel"/><h2>Pending Elevation Sign-offs (2)</h2></header>{[['Blessing Chirume','ESCROW_EXPORT'],['Farai Sibanda','SANCTION_OVERRIDE']].map(([name,request])=><article key={request}><div><strong>{name}</strong><small>{request} · Reference request</small></div><button disabled>Sign & Approve</button><button disabled>Reject</button></article>)}</section></div>
  <section className="rbac-breakglass"><Icon name="e911_emergency"/><div><h2>Break-Glass Emergency Protocol</h2><p>Emergency access requires a separately designed, server-enforced quorum and immutable audit path. It is unavailable in this interface.</p></div><b>SEALED · NO UI BYPASS</b></section>
 </div>
}
