import { useMemo, useState } from 'react';

type Account = { id: string; name: string; initials: string; location: string; province: string; registered: string; nationalId: string; taxId: string; phone: string; email: string; tier: number; tierLabel: string; trust: number; kyc: string; commerce: string; usd: string; zig: string; ledger: string; signal: string; detail: string; state: string };
const accounts: Account[] = [
  { id: 'PAM-8849-ZW', name: 'Farai Mutasa', initials: 'FM', location: 'Borrowdale West, Harare', province: 'Harare', registered: '14-Nov-2022', nationalId: '63-2940182-K-19', taxId: '200-91829-01', phone: '+263 77 289 4410 (Econet)', email: 'mutasa.farai@zimgrow.co.zw', tier: 3, tierLabel: 'L3 DIRECTOR', trust: 96, kyc: 'EcoCash KYC: MATCHED', commerce: '14 Listings · 1 Store', usd: '$3,450.00', zig: '14,200.00', ledger: 'Across 3 active trades', signal: 'CLEAN RECORD', detail: 'AAL2 Authenticated', state: 'Clean' },
  { id: 'PAM-4109-BYO', name: 'Chipo Sibanda', initials: 'CS', location: 'Suburbs, Bulawayo', province: 'Bulawayo', registered: '02-Mar-2023', nationalId: '08-1188391-M-08', taxId: 'UNREGISTERED', phone: '+263 71 902 1198 (NetOne)', email: 'chipo.sibanda98@gmail.com', tier: 2, tierLabel: 'L2 NATIONAL ID', trust: 64, kyc: 'OneMoney Name Mismatch', commerce: '28 Listings · 0 Stores', usd: '$820.00', zig: '0.00', ledger: '$400 disputed', signal: 'MULTI-IMEI CONFLICT', detail: '3 Accounts from 1 Device', state: 'Watchlist' },
  { id: 'PAM-9204-CHIT', name: 'Kudzai Nyamhunga', initials: 'KN', location: 'Unit C, Chitungwiza', province: 'Harare', registered: '18-Jan-2024', nationalId: '63-1002931-E-42 (FLAGGED)', taxId: 'N/A - FRAUD WATCH', phone: '+263 77 501 9921 (Econet)', email: 'zimdeals247@temp-mail.org', tier: 2, tierLabel: 'SANCTION FROZEN', trust: 12, kyc: 'EcoCash ID Mismatch', commerce: '2 Listings (Frozen)', usd: '$1,190.00', zig: '0.00', ledger: 'Locked · Escrow Dispute #DIS-449', signal: 'HONEYPOT HIT', detail: 'Fake Land Deed Injected', state: 'Sanctioned' },
  { id: 'PAM-1994-MUT', name: 'Tendai Marange', initials: 'TM', location: 'Morningside, Mutare', province: 'Manicaland', registered: '09-Aug-2021', nationalId: '75-3991821-B-75', taxId: '109-44021-99', phone: '+263 77 114 8009 (Econet)', email: 't.marange@manicalandautos.co.zw', tier: 3, tierLabel: 'L3 FLEET DEALER', trust: 99, kyc: 'CBZ Bank Direct KYC', commerce: '42 Listings · 2 Showrooms', usd: '$48,200.00', zig: '0.00', ledger: 'Volume · Escrow Complete: 100%', signal: 'CERTIFIED DEALER', detail: 'No Escalations 180d', state: 'Clean' },
  { id: 'PAM-5501-GWE', name: 'Ruvimbo Gwenzi', initials: 'RG', location: 'Southdowns, Gweru', province: 'Midlands', registered: '08-Apr-2024', nationalId: 'PENDING UPLOAD', taxId: 'NONE', phone: '+263 73 349 1092 (Telecel)', email: 'ruvi.gwenzi@outlook.com', tier: 1, tierLabel: 'L1 PHONE OTP', trust: 45, kyc: 'Tier 2 ID Required', commerce: '1 Listing (Farm Produce)', usd: '$45.00', zig: '0.00', ledger: 'Max Escrow: $100.00', signal: 'NEW REGISTER', detail: 'Joined 3 days ago (sample)', state: 'Clean' },
];
const provinces = ['Harare', 'Bulawayo', 'Manicaland', 'Midlands', 'Masvingo', 'Mashonaland East', 'Mashonaland West', 'Mashonaland Central', 'Matabeleland North', 'Matabeleland South'];
function Icon({ name }: { name: string }) { return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>; }

export function UserDirectoryPage() {
  const [query, setQuery] = useState('');
  const [tier, setTier] = useState('All');
  const [state, setState] = useState('All');
  const [province, setProvince] = useState('All');
  const [selectedId, setSelectedId] = useState(accounts[0].id);
  const [checked, setChecked] = useState<Set<string>>(new Set());
  const [compact, setCompact] = useState(true);
  const shown = useMemo(() => accounts.filter(user => (tier === 'All' || user.tier === Number(tier)) && (state === 'All' || user.state === state) && (province === 'All' || user.province === province) && `${user.name} ${user.id} ${user.nationalId} ${user.phone} ${user.email} ${user.location}`.toLowerCase().includes(query.trim().toLowerCase())), [query, tier, state, province]);
  const selected = accounts.find(user => user.id === selectedId)!;
  const visibleChecked = shown.filter(user => checked.has(user.id)).length;
  function reset() { setQuery(''); setTier('All'); setState('All'); setProvince('All'); }
  function toggle(id: string) { setChecked(previous => { const next = new Set(previous); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function toggleVisible() { setChecked(previous => { const next = new Set(previous); shown.forEach(user => { if (visibleChecked === shown.length) next.delete(user.id); else next.add(user.id); }); return next; }); }
  return <div className={`directory-page ${compact ? 'compact' : ''}`}>
    <div className="directory-reference" role="note"><Icon name="science" /><b>REFERENCE IDENTITY DATA</b><span>Accounts, identity numbers, balances and signals are design samples. Registry verification and enforcement are not connected.</span></div>
    <div className="directory-breadcrumb">PAMARKET OPS / DIRECTORY & COMMERCE / <b>USER MANAGEMENT & IDENTITY</b><span>ID VERIFIER: NOT CONNECTED</span></div>
    <header className="directory-hero"><div><small>SEC-OPS REGISTRY · KYC & IDENTITY REVIEW</small><h1>User Directory & Identity Management</h1><p>Inspect accounts, carrier KYC tiers, merchant identity, and enforcement signals across active marketplaces.</p></div><nav aria-label="Registry actions"><button disabled><Icon name="file_download" />EXPORT AUDIT (CSV)</button><button disabled><Icon name="fingerprint" />RG-OFFLINE CACHE</button><button disabled><Icon name="security_update_good" />+ ENROLL KYC EXCEPTION</button></nav></header>
    <section className="directory-kpis" aria-label="Reference account metrics">{[
      ['Total Accounts Enrolled', '148,290', 'badge', '+12.4% MoM', 'Active last 24h: 38,194'],
      ['KYC L3 Verified Merchants', '1,420', 'verified_user', 'DIRECTOR VALID', 'ZIMRA Tax Cleared: 98.1%'],
      ['Watchlist / High Risk Signals', '47', 'crisis_alert', 'SURVEILLANCE', 'Honeypot Decoy: 12 · IMEI Spoof: 9'],
      ['Active Sanctions & Freezes', '19', 'gavel', 'FUNDS FROZEN', 'Escrow Trapped: $41,200 USD'],
    ].map(([label, value, icon, badge, detail], index) => <article key={label} className={index > 1 ? 'alert' : ''}><header>{label}<Icon name={icon} /></header><div><strong>{value}</strong><b>{badge}</b></div><footer>{detail}<span>SAMPLE</span></footer></article>)}</section>
    <section className="directory-filters" aria-label="User filters"><div><label className="directory-search"><Icon name="person_search" /><input aria-label="Search users" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name, ID, phone, email or account" /></label><select aria-label="KYC tier" value={tier} onChange={event => setTier(event.target.value)}><option value="All">KYC TIER: ALL TIERS</option><option value="3">TIER 3 - BIOMETRIC & DIRECTOR</option><option value="2">TIER 2 - NATIONAL ID VERIFIED</option><option value="1">TIER 1 - PHONE & ECOCASH</option><option value="0">TIER 0 - UNVERIFIED GUEST</option></select><select aria-label="Enforcement state" value={state} onChange={event => setState(event.target.value)}><option value="All">ENFORCEMENT: ALL STATES</option><option value="Clean">CLEAN / IN GOOD STANDING</option><option value="Watchlist">WATCHLIST / FLAGGED</option><option value="Sanctioned">SANCTIONED ESCROW</option><option value="De-registered">PERMANENTLY DE-REGISTERED</option></select><select aria-label="Province" value={province} onChange={event => setProvince(event.target.value)}><option value="All">PROVINCE: ALL ZIMBABWE</option>{provinces.map(item => <option key={item}>{item}</option>)}</select><button onClick={reset} aria-label="Reset user filters"><Icon name="restart_alt" /></button></div><footer><span>ACTIVE CONSTRAINTS:</span>{tier !== 'All' && <button onClick={() => setTier('All')}>TIER {tier} ×</button>}{state !== 'All' && <button onClick={() => setState('All')}>{state.toUpperCase()} ×</button>}{province !== 'All' && <button onClick={() => setProvince('All')}>{province.toUpperCase()} ×</button>}{query && <button onClick={() => setQuery('')}>SEARCH: {query} ×</button>}{tier === 'All' && state === 'All' && province === 'All' && !query && <span>NONE</span>}<button onClick={reset}>Clear all parameters</button></footer></section>
    <div className="directory-workspace"><section className="directory-ledger"><header><span aria-live="polite">VIEWING {shown.length} OF {accounts.length} REFERENCE ENTITIES</span><button aria-pressed={compact} onClick={() => setCompact(value => !value)}><Icon name="view_column" />DENSITY: {compact ? 'COMPACT' : 'COMFORTABLE'}</button></header><div className="directory-table-scroll"><table aria-label="User identity registry"><thead><tr><th scope="col">Select</th>{['User Profile & Location', 'Identity & Carrier', 'KYC & Trust', 'Commerce Escrow', 'System Signals', 'Enforcement'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{shown.map(user => <tr key={user.id} className={`${user.state.toLowerCase()} ${selectedId === user.id ? 'selected' : ''}`}><td><input type="checkbox" aria-label={`Select ${user.name}`} checked={checked.has(user.id)} onChange={() => toggle(user.id)} /></td><td><div className="directory-person"><span className="directory-avatar">{user.initials}</span><div><strong>{user.name}</strong><small>{user.location}</small><code>{user.id}</code></div></div></td><td><strong>ID: {user.nationalId}</strong><small>{user.phone}</small><small>{user.email}</small></td><td><b className="directory-tier">{user.tierLabel}</b><div className="directory-trust"><span style={{ width: `${user.trust}%` }} /></div><strong>{user.trust}%</strong><small>{user.kyc}</small></td><td><strong>{user.commerce}</strong><small>{user.usd} USD {user.id === 'PAM-1994-MUT' ? 'Volume' : 'Escrow'}</small><small>{user.ledger}</small></td><td><b className="directory-signal">{user.signal}</b><small>{user.detail}</small></td><td><button aria-label={`Dossier for ${user.name}`} aria-pressed={selectedId === user.id} onClick={() => setSelectedId(user.id)}>DOSSIER</button><button disabled>{user.state === 'Sanctioned' ? 'FROZEN' : user.state === 'Watchlist' ? 'SANCTION' : 'MANAGE'}</button></td></tr>)}</tbody></table>{shown.length === 0 && <div className="directory-empty" role="status">No reference accounts match these filters. <button onClick={reset}>Clear filters</button></div>}</div><footer><label><input type="checkbox" aria-label="Select all visible users" checked={shown.length > 0 && visibleChecked === shown.length} ref={element => { if (element) element.indeterminate = visibleChecked > 0 && visibleChecked < shown.length; }} onChange={toggleVisible} disabled={!shown.length} />Select All Visible ({shown.length})</label><span aria-live="polite">{checked.size} selected · {visibleChecked} visible</span><button disabled>Bulk National ID Resync</button><button disabled>Bulk Sanction Freeze</button></footer></section>
      <aside className="directory-inspector" aria-label="Entity dossier"><header><Icon name="contact_emergency" /><div><small>ENTITY DOSSIER</small><strong>{selected.id}</strong></div><b>{selected.tierLabel}</b></header><section className="directory-identity"><div className="directory-person"><span className="directory-avatar">{selected.initials}</span><div><h2>{selected.name}</h2><b>{selected.state.toUpperCase()} · SAMPLE</b></div></div><p>{selected.location} · Registered {selected.registered}</p><dl><div><dt>NATIONAL ID REG</dt><dd>{selected.nationalId}</dd></div><div><dt>ZIMRA BP #</dt><dd>{selected.taxId}</dd></div></dl></section><section><h3>ACTIVE CLIENT SESSIONS & NETWORKS</h3>{selected.id === 'PAM-8849-ZW' ? <><article className="directory-session"><Icon name="laptop_mac" /><div><strong>Apple MacBook Pro M2 (Ventura)</strong><small>HW-TOKEN AAL2 · SAMPLE SESSION</small><p>Network: Liquid Telecom Zimbabwe<br />Location: Harare CBD</p></div></article><article className="directory-session"><Icon name="smartphone" /><div><strong>Samsung Galaxy S23 Ultra</strong><small>Econet 5G · SAMPLE SESSION</small><p>Location: Harare Borrowdale</p></div></article></> : <p>No session evidence connected for this reference account.</p>}<button disabled>Force Kill Session</button></section><section><h3>FINANCIAL LEDGER & ESCROW RESERVES</h3><div className="directory-balances"><article><small>{selected.id === 'PAM-1994-MUT' ? 'COMMERCE VOLUME' : 'ESCROW HELD'} (USD)</small><strong>{selected.usd}</strong><p>{selected.ledger}</p></article><article><small>ESCROW HELD (ZIG)</small><strong>{selected.zig}</strong><p>Reference balance</p></article></div><p>{selected.kyc} · SAMPLE</p></section><section><h3>GOVERNANCE AUDIT TRAIL</h3>{selected.id === 'PAM-8849-ZW' ? <ol className="directory-timeline"><li><strong>L3 Director Biometrics Verified</strong><small>04-Jan-2024 · Sample audit entry</small></li><li><strong>Hardware Token Enrolled (Yubikey 5C)</strong><small>12-Nov-2023 · Sample audit entry</small></li><li><strong>Econet Mobile KYC Auto-Cleared</strong><small>14-Nov-2022 · Sample audit entry</small></li></ol> : <p>No audit evidence connected for this reference account.</p>}</section><section className="directory-commands"><h3>COMMAND SANCTIONS & OVERRIDES</h3><div>{[['lock_reset', 'RESET 2FA TOKEN'], ['history_toggle_off', 'DOWNGRADE KYC'], ['warning', 'FREEZE ESCROW'], ['block', 'BAN & SUSPEND']].map(([icon, label]) => <button key={label} disabled><Icon name={icon} />{label}</button>)}</div><p>Identity changes, session revocation and sanctions require connected, audited server handlers.</p></section></aside>
    </div>
  </div>;
}
