import { useMemo, useState } from 'react';

type Fleet = { id:string; operator:string; location:string; province:string; vehicleClass:string; fleet:string; permit:string; rentals:string; escrow:string; risk:'Normal'|'Critical'|'Disconnected'; riskDetail:string; alert?:{vehicle:string;plate:string;distance:string;signal:string;hirer:string;identity:string;payment:string;destination:string} };
const fleets:Fleet[]=[
  {id:'RNT-8812',operator:'ZimDrive Safari & Fleet',location:'Harare Central · 2nd Ave Hub',province:'Harare',vehicleClass:'4X4 Safari / Overland',fleet:'24 Vehicles · 18 LandCruiser, 6 Hilux',permit:'VALID · EXP 2026',rentals:'18 / 24 · 75% Load',escrow:'$12,400 USD · 12 bonds',risk:'Normal',riskDetail:'NORMAL · 0 ALERTS'},
  {id:'RNT-8805',operator:'Beitbridge 4x4 Hire',location:'Beitbridge Border Road Complex',province:'Matabeleland South',vehicleClass:'4X4 Safari / Overland',fleet:'8 Vehicles · 1 Jammed Hilux GD-6',permit:'PENDING RENEWAL',rentals:'5 / 8 · 1 anomaly',escrow:'$3,500 USD · BOND FROZEN',risk:'Critical',riskDetail:'CRITICAL BORDER HOOK',alert:{vehicle:'Toyota Hilux 2.8 GD-6',plate:'AFK-9022-ZW',distance:'11.8 km to Chirundu border',signal:'GPS / OBD signal lost · sample',hirer:'Kudzai Brian Mutasa',identity:'Reference ID risk flag',payment:'EcoCash USD · $3,500 locked',destination:'Kariba Recreational Park'}},
  {id:'RNT-8791',operator:'Sunshine City Car Hire',location:'Robert Gabriel Mugabe Intl Airport',province:'Harare',vehicleClass:'Executive Sedans',fleet:'15 Vehicles · Fortuner, Corolla Cross',permit:'VALID',rentals:'9 / 15',escrow:'$4,500 USD · inspection cleared',risk:'Normal',riskDetail:'LOW RISK'},
  {id:'RNT-8760',operator:'Matopos Overland Rentals',location:'Bulawayo Industrial Site',province:'Bulawayo',vehicleClass:'4X4 Safari / Overland',fleet:'12 LandCruisers · Heavy Duty 70 Series',permit:'VALID',rentals:'11 / 12 · 91% Load',escrow:'$8,800 USD · 11 pledges',risk:'Normal',riskDetail:'NORMAL'},
  {id:'RNT-8744',operator:'Eastern Highlands Executive Hire',location:'Mutare CBD',province:'Manicaland',vehicleClass:'Executive Sedans',fleet:'9 Vehicles · 1 OBD disconnected',permit:'VALID',rentals:'6 / 9',escrow:'$2,100 USD · 6 bonds',risk:'Disconnected',riskDetail:'GPS JAMMED / OBD LOST'},
];
function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>}
export function VehicleRentalsPage(){
  const [query,setQuery]=useState(''); const [province,setProvince]=useState('All'); const [vehicleClass,setVehicleClass]=useState('All'); const [risk,setRisk]=useState('All'); const [selectedId,setSelectedId]=useState(fleets[1].id);
  const shown=useMemo(()=>fleets.filter(item=>(province==='All'||item.province===province)&&(vehicleClass==='All'||item.vehicleClass===vehicleClass)&&(risk==='All'||item.risk===risk)&&`${item.id} ${item.operator} ${item.location} ${item.fleet}`.toLowerCase().includes(query.trim().toLowerCase())),[query,province,vehicleClass,risk]);
  const selected=fleets.find(item=>item.id===selectedId)??fleets[1]; const alert=selected.alert;
  const reset=()=>{setQuery('');setProvince('All');setVehicleClass('All');setRisk('All')};
  return <div className="rentals-page">
    <div className="rentals-reference" role="note"><Icon name="science"/><b>REFERENCE FLEET DATA</b><span>Operators, vehicle positions, identity checks and balances are design fixtures. No OBD, government, payment or police integration is connected.</span></div>
    <div className="rentals-breadcrumb">PAMARKET OPS / DIRECTORY & COMMERCE / <b>VEHICLE RENTALS & FLEET VERIFICATION</b><span>CAN-BUS FEED: NOT CONNECTED</span></div>
    <header className="rentals-hero"><div><h1>Rental Car Operators & Fleet Verification Queue</h1><p>Review operator licensing, fleet tracking signals, border-risk alerts and reference escrow damage bonds.</p></div><button disabled><Icon name="add_box"/>Register Fleet Operator</button></header>
    <section className="rentals-kpis">{[['corporate_fare','Enrolled Operators','118','VID LICENSED: 94.2%'],['directions_car','Active Fleet Telemetry','842','OBD STATUS: REFERENCE'],['fmd_bad','Border Proximity Breach','04','CRITICAL BREACHES'],['account_balance','Active Escrow Damage Bonds','$64,500 USD','REFERENCE POOL']].map(([icon,label,value,note],i)=><article key={label} className={i===2?'danger':''}><header>{label}<Icon name={icon}/></header><strong>{value}</strong><p>{note}</p><footer>SAMPLE DATA <b>{i===2?'ACTIONS DISABLED':'NOT LIVE'}</b></footer></article>)}</section>
    <section className="rentals-filters" aria-label="Fleet filters"><label><Icon name="search"/><input aria-label="Search rental fleets" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search operator, fleet, location or ID"/></label><select aria-label="Fleet province" value={province} onChange={e=>setProvince(e.target.value)}><option value="All">PROVINCE: ALL ZIMBABWE</option>{[...new Set(fleets.map(x=>x.province))].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Vehicle class" value={vehicleClass} onChange={e=>setVehicleClass(e.target.value)}><option value="All">CLASS: ALL CLASSES</option>{[...new Set(fleets.map(x=>x.vehicleClass))].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Fleet risk" value={risk} onChange={e=>setRisk(e.target.value)}><option value="All">GPS STATUS: ALL CONDITIONS</option><option>Critical</option><option>Disconnected</option><option>Normal</option></select><button onClick={reset}><Icon name="restart_alt"/>Clear Filters</button></section>
    <section className="rentals-ledger"><div className="rentals-table-scroll"><table aria-label="Rental operator verification queue"><thead><tr>{['Operator / Key','Fleet Audit','VID Ministry Permit','Active Rentals','Escrow Bond Held','Geo-Risk Vector','Tactical Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(item=><tr key={item.id} className={`${item.risk.toLowerCase()} ${selected.id===item.id?'selected':''}`}><td><strong>#{item.id}</strong><b>{item.operator}</b><small>{item.location}</small></td><td><span>{item.fleet}</span></td><td><b>{item.permit}</b></td><td><strong>{item.rentals}</strong></td><td><strong>{item.escrow}</strong></td><td><b>{item.riskDetail}</b>{item.alert&&<small>{item.alert.distance}</small>}</td><td><button aria-label={`Inspect ${item.id}`} onClick={()=>setSelectedId(item.id)}><Icon name="map"/>{item.alert?'Inspect Alert':'Fleet Audit'}</button><button disabled>{item.alert?'IMMOBILIZE':'MANAGE'}</button></td></tr>)}</tbody></table>{!shown.length&&<div className="rentals-empty" role="status">No reference fleet operators match these filters. <button onClick={reset}>Clear filters</button></div>}</div><footer>SHOWING {shown.length} OF {fleets.length} REFERENCE OPERATORS <span>FLEET API: NOT CONNECTED</span></footer></section>
    <section className={`rentals-incident ${alert?'active':''}`} aria-label="Fleet incident inspector"><header><Icon name={alert?'warning':'directions_car'}/><div><small>{alert?'INCIDENT FLAGGED':'FLEET DOSSIER'}</small><h2>{selected.operator} · #{selected.id}</h2></div><b>{alert?'REFERENCE ALERT':'NO ACTIVE ALERT'}</b></header>{alert?<div className="rentals-incident-grid"><article><h3>TARGET VEHICLE</h3><strong>{alert.vehicle} [{alert.plate}]</strong><dl><div><dt>SIGNAL</dt><dd>{alert.signal}</dd></div><div><dt>PROXIMITY</dt><dd>{alert.distance}</dd></div><div><dt>FLEET</dt><dd>{selected.fleet}</dd></div></dl><div className="rentals-radar"><Icon name="radar"/><strong>CHIRUNDU BORDER CORRIDOR</strong><span>{alert.distance} · LOCATION NOT LIVE</span></div></article><article><h3>HIRER IDENTITY & RISK CHECK</h3><strong>{alert.hirer}</strong><dl><div><dt>IDENTITY</dt><dd>{alert.identity}</dd></div><div><dt>ESCROW PAYMENT</dt><dd>{alert.payment}</dd></div><div><dt>DESTINATION DECLARED</dt><dd>{alert.destination}</dd></div><div><dt>CARRIER PERMIT</dt><dd>Not connected</dd></div></dl><div className="rentals-actions"><button disabled><Icon name="no_encryption"/>Trigger Engine Kill-Switch</button><button disabled><Icon name="local_police"/>Alert ZRP & Border Post</button><button disabled><Icon name="gavel"/>Forfeit Escrow Deposit</button></div></article></div>:<p className="rentals-clear">This reference operator has no active fleet incident. Select a flagged operator to inspect the sample alert.</p>}</section>
  </div>
}
