'use strict';
const fs=require('fs');const path=require('path');const{DIST,walkFiles}=require('./file-utils');
function validatePage(relative,generated){const html=fs.readFileSync(path.join(DIST,relative),'utf8'),missing=[];if(!/<title>[^<]+<\/title>/i.test(html))missing.push('title');if(!/<meta[^>]+name=["']description["'][^>]+content=["'][^"']+/i.test(html))missing.push('description');if(!/<link[^>]+rel=["']canonical["'][^>]+href=["']https:\/\/pamarketzw\.com\//i.test(html))missing.push('canonical');if(!/<meta[^>]+property=["']og:title["']/i.test(html))missing.push('og:title');if(!/<meta[^>]+property=["']og:url["']/i.test(html))missing.push('og:url');if(!/<meta[^>]+name=["']twitter:(card|title)["']/i.test(html))missing.push('twitter');const jsonLd=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];for(const m of jsonLd)try{JSON.parse(m[1]);}catch(_){missing.push('valid JSON-LD');}if(generated&&!jsonLd.length)missing.push('JSON-LD');return missing;}
function validateSeo(){const blocking=[],advisory=[];for(const relative of ['index.html','browse.html']){const m=validatePage(relative,false);if(m.length)blocking.push(relative+': '+m.join(', '));}for(const dir of ['l','b','r']){const sample=walkFiles(path.join(DIST,dir)).filter(x=>x.endsWith('.html')).sort()[0];if(!sample){blocking.push(dir+': no generated page');continue;}const relative=dir+'/'+sample,m=validatePage(relative,true);if(m.length)blocking.push(relative+': '+m.join(', '));}for(const relative of walkFiles(DIST).filter(x=>x.endsWith('.html')&&!/^(l|b|r)\//.test(x))){const m=validatePage(relative,false);if(m.length&&!['index.html','browse.html'].includes(relative))advisory.push(relative+': '+m.join(', '));}if(blocking.length)throw new Error('Critical SEO validation failed:\n'+blocking.join('\n'));return{blockingFailures:0,advisory};}
const validateSeoBase=validateSeo;
validateSeo=function(){return validateSeoBase();};
// Titles may carry an id used by dynamic category pages.
const validatePageBase=validatePage;
validatePage=function(relative,generated){const missing=validatePageBase(relative,generated);const html=fs.readFileSync(path.join(DIST,relative),'utf8');return /<title(?:\s[^>]*)?>[^<]+<\/title>/i.test(html)?missing.filter(x=>x!=='title'):missing;};
if(require.main===module)console.log(JSON.stringify(validateSeo(),null,2));module.exports={validateSeo};
